export THISDIR="`pwd`"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${THISDIR}/lib
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${THISDIR}/lib
export PATH=${PATH}:${THISDIR}/bin


export NTUPLEPKGDIR="${THISDIR}/../NtuplePackage/"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NTUPLEPKGDIR}/lib
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${NTUPLEPKGDIR}/lib
export PATH=${PATH}:${NTUPLEPKGDIR}/bin
export PATH=${PATH}:${NTUPLEPKGDIR}/scripts

export NTUPLEPKGINCLUDE=${NTUPLEPKGDIR}/interface
export NTUPLEPKGLIB=${NTUPLEPKGDIR}/lib
